name: Hello World
on:
  push:
    branches:
    - main
    - release/*
    

jobs:
  System_Info:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, World!"
      
    - name: Show OS Info
      run: cat /etc/os-release

    - name: Show Date and Time
      run: date
